packages:
  - "apps/*"
  - "packages/*"

catalog:
  react-hook-form: ^7.54.2
  lucide-react: ^0.456.0
  tailwindcss: ^3.4.13
  eslint: ^8.57.0
  prettier: ^3.4.1
  typescript: ^5.6.3
  "@types/node": ^20
  "@types/eslint": ^8
  next: ^15.1.3
  "@next/eslint-plugin-next": ^15.1.3

catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.0
    "@types/react-dom": ^19.1.0
