export const PLANS = [
  {
    name: "FREE",
    price: 0,
    description: "Perfect for trying out our service",
    features: [
      "3 workspaces",
      "30-day analytics retention",
      "5k tracked clicks/month",
      "5 domains",
      "3 users",
      "Basic support",
      "Community Access",
      "API access",
    ],
    isPopular: false,
    buttonText: "Get Started",
    pricingButtonText: "Current Plan",
  },
  {
    name: "PRO",
    price: 15,
    description: "For professionals and growing teams",
    features: [
      "Everything in Free",
      "Upto 10 workspaces",
      "Upto 50k tracked clicks/month",
      "1 year analytics retention",
      "15 domains",
      "10 users",
      "Advanced Link features",
      "Priority support",
      "Team collaboration",
    ],
    isPopular: true,
    buttonText: "Get Pro",
    pricingButtonText: "Upgrade to Pro",
  },
  {
    name: "ENTERPRISE",
    price: 40,
    description: "For large organizations with advanced needs",
    features: [
      "Everything in Pro",
      "Upto 50 workspaces",
      "Upto 100k tracked clicks/month",
      "3 year analytics retention",
      "50 domains",
      "30 users",
      "Real-time Event streaming",
      "Real-time webhook",
    ],
    isPopular: false,
    buttonText: "Get Business",
    pricingButtonText: "Upgrade to Enterprise",
  },
];
